// <auto-generated />
using System;
using CitiesManager.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.API.Models.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("23b46d49-25ec-4b04-be3a-ea73f5a3d5d1"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityID = new Guid("d0c788c0-6f24-4084-974d-79ebdcf352b7"),
                            CityName = "London"
                        },
                        new
                        {
                            CityID = new Guid("2e0e0e68-72e5-416b-a21b-ac97e25bee17"),
                            CityName = "Hamburg"
                        },
                        new
                        {
                            CityID = new Guid("f70d6086-17c4-4f49-9bcb-41a3382ea991"),
                            CityName = "Tehran"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
